### PR TITLE
Add osl_string_concat and osl_generic_nclone functions

### PR DESCRIPTION
**Pull request by Haerezis**

### CODE REVIEW

**Comment by Lnc** [comment]
Thank you for your pull request.

The code seems ok.

The name of the function "void osl_strings_concat(osl_strings_p * dest, osl_strings_p str1, osl_strings_p str2);" is ambiguous.
Can you replace "osl_strings_concat" by "void osl_strings_add_strings(osl_strings_p dest, osl_strings_p strings);"? The utilization is a little bit different.

See OpenScop documentation https://www.lri.fr/~bagneres/files/tools/openscop/openscop.pdf section 4.6.3 for coding style.

**Comment by Haerezis** [comment]
I've made the change. You're right, osl_string_concat was ambiguous, but I didn't have any other ideas :/

**Comment by Haerezis** [comment]
I've talked to @Ced about the naming convention.
He would like to change all the "nclone" function to "clone_n" and all the print functions I've added would also be like ``osl_something_print_n``.
I also have to make the change in the tool of periscop to use ``clone_n`` instead of ``nclone``, but ``nclone`` doesn't seem to be used that much in those.

Maybe you would like to have a new pull request for that?

**Comment by ftynse** [comment]
grep finds around 10 occurrences of nclone in other projects...

I think the proper division for pull requests is the following:
- osl_strings_add_strings + osl_generic_nclone (without any other function)
- extra functions named as osl_something_something_n
- rename nclone to clone_n in all projects

The last pull request to be accepted simultaneously for all projects, right after which we bump minor versions of all tools.

**Comment by Haerezis** [comment]
Yeah, that was also my opinion.
Because I fixed some things related to osl_generic_nclone in the last commits, do you want me to create a new pull request for "osl_strings_add_strings + osl_generic_nclone" where the right commits are cherry picked?

Then I'll create another one for extra function "osl_something_something_n".

Then a last one for nclone to clone_n.

Sounds good to you?

**Comment by ftynse** [comment]
Yes.
Hope it does not bother you too much, this way the history is cleaner.

**Comment by Haerezis** [comment]
No not at all.
It's even my fault for committing in the same branch the osl_string/osl_generic_nclone function and the print_n function.
I'm still not used to pull request :/

**Pull request closed without merging**
